org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=perspatium
mod_version=1.20.1-2.0.0
mod_name=Ad Astra: Per Spatium Et Tempus
mod_description=An addon for Ad Astra, Stellaris and Galacticraft adding new structures to improve space exploration.
mod_license=All Rights Reserved

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_group_id=net.pastek.perspatium
mod_authors=Roi_Pasteque